### ISSUE TITLE
crash when property is undefined

### ISSUE THREAD

**Issue by Bonuspunkt** [caohanyang/json_diff_rfc6902#2]
``` js
const { diff } = require('json-diff-rfc6902');

const before = {
    a: 'text',
}
const after = {
    a: 'text',
    b: undefined
};

diff(before, after);
```
crashes with
```
.\node_modules\json-diff-rfc6902\lib\unchangedArea.js:71
    if (newValue.toString() === value) {
                ^

TypeError: Cannot read property 'toString' of undefined
    at Object.findValueInUnchanged (.\node_modules\json-diff-rfc6902\lib\unchangedArea.js:71:17)
    at generateObjectDiff (.\node_modules\json-diff-rfc6902\JSON-Diff.js:127:35)
    at generateDiff (.\node_modules\json-diff-rfc6902\JSON-Diff.js:51:5)
    at diff (.\node_modules\json-diff-rfc6902\JSON-Diff.js:33:3)
```

**Comment by caohanyang** [comment]
Thanks! 
I will fix it later.

**Comment by nlac** [comment]
Not sure it is really an issue. Keep in mind that the value _undefined_ is an illegal JSON node, see 
[here](https://en.wikipedia.org/wiki/JSON#Unsupported_native_data_types)  and [here](http://www.json.org/) so don't expect any diff for that input - dropping an exception is reasonable, however the library may drop some more friendly one saying "invalid input" or stg like that.

**Comment by caohanyang** [comment]
Undefined is not a valid json value, even though it is valid in javascript. 
From the [official json standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) (ECMA-404, Section 5):
**A JSON value can be an object, array, number, string, true, false, or null.**

I will give some friendly output in the next version.

Thanks!
